name: Windows Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.4'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        run: flutter build windows --release

      - name: Show Release Folder
        shell: pwsh
        run: |
          Get-ChildItem build/windows/x64/runner/Release -Recurse

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/windows/x64/runner/Release/*.exe

          
  ##################################
  ## macOS
  ##################################

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.4"

      - run: flutter pub get

      - run: flutter config --enable-macos-desktop

      - run: flutter build macos --release

      # Install create-dmg
      - run: brew install create-dmg

      # Create DMG
      - name: Build DMG
        run: |
          mkdir dmg

          cp -R build/macos/Build/Products/Release/*.app dmg/

          create-dmg \
            --volname "Tray" \
            --window-pos 200 120 \
            --window-size 800 500 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            Tray.dmg \
            dmg/

      - uses: softprops/action-gh-release@v2
        with:
          files: Tray.dmg
